---
abstract: 'NexStarCtl - API to control NexStar compatible telescopes'
author:
  - 'Rumen Bogdanovski <rumen@skyarchive.org>'
build_requires:
  Device::SerialPort: 0.1
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.66, CPAN::Meta::Converter version 2.120921'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: NexStarCtl
no_index:
  directory:
    - t
    - inc
requires:
  Device::SerialPort: 0.1
version: 0.12
